import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";  
import DarkModeToggle from "@/components/DarkModeToggle/DarkModeToggle";
import {ThemeProvider} from "@/context/ThemeContext"  

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Class Project",
  description: "Generated by create next app",     
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>  
        <ThemeProvider>
        <Navbar/>   
        <DarkModeToggle/>    
        {children}    
        Footer                     
        </ThemeProvider>
        </body>     
    </html>
  );
}
